GH_PROXY="https://g.ioiox.com/"
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Rainboylvx/RainboyVim
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Yggdroot/indentLine
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Rainboylvx/rSnip
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/yianwillis/vimcdoc
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/romainl/vim-cool
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/thinca/vim-quickrun
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/ludovicchabant/vim-gutentags
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/morhetz/gruvbox
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/digitaltoad/vim_Pug
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/bling/vim-airline
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/vim-airline/vim-airline-themes
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Linfee/ultisnips-zh-doc
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/SirVer/ultisnips
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Valloric/MatchTagAlways
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/octol/vim-cpp-enhanced-highlight
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Valloric/ListToggle
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/nathanaelkane/vim-indent-guides
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/kshenoy/vim-signature
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/danro/rename.vim
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/Lokaltog/vim-easymotion
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/junegunn/vim-easy-align
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/scrooloose/nerdcommenter
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/scrooloose/nerdtree
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/vim-scripts/taglist.vim
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/gcmt/wildfire.vim
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/luochen1990/rainbow
git -C $HOME/.vim/plugged clone --depth 1  ${GH_PROXY}https://github.com/907th/vim-auto-save
git -C $HOME/.vim/plugged clone --depth 1 -b release  ${GH_PROXY}https://github.com/neoclide/coc.nvim
